<?php 
	require_once("commonCode.php");
?>
<!DOCTYPE html>
<html>
<head>
	<title>Policy | bengal Gazette</title>
	<link rel="stylesheet" type="text/css" href="CSS/commonCode.css">
	<link rel="stylesheet" type="text/css" href="CSS/policy.css">
</head>
<body>
	<div id="main_body" style="background-color: #ffffff;">
		<?php TITLE_LOGO(); ?>
		<?php NAVIGATION_BAR(); ?>
		<div id="policy_list">
		<h4>Privacy Policy of <i>Bengal Gazette</i></h4>
		<p>Bengal Gazette is committed to protecting your personal information when you are 
			using the website of Bengal Gazette or an application developed by Bengal Gazette. 
			This privacy policy relates to use of any personal information that it collects 
			from visitors/readers via following, among other, services:
			<ul>
    			<li>any Bengal Gazette website that links to this privacy and cookies policy;</li>
    			<li>social media or official Bengal Gazette content on other websites;</li>
    			<li>mobile device and/or applications (“Apps”)</li>
			</ul>
		</p>

		<p>In all the above services, the privacy policy shall apply only when the application,
		website or contents therein are generated by Bengal Gazette.</p>

		<p>Bengal Gazette collects or receives information about its users for many purposes; 
		for instance, to provide services designed to serve the user, to monitor and improve the
		services offerings, for marketing or targeting advertisement etc. Such information may 
		include your name, address, phone number, email address, age, social network account etc. 
		(“the Information”).</p>

		<p>There may be other privacy policies that apply to certain services provided by Bengal
		Gazette. Visitors are requested to read these while registering or subscribing to these
		services on these sites. It is Bengal Gazette’s endeavor to protect the information received 
		from its visitors/readers. Bengal Gazette respects privacy of its visitors/readers and makes 
		use its best effort to ensure that the information collected is used for the limited purpose 
		for which it was received.</p>

		<h4>How <i>Bengal Gazette</i> collects the information</h4>
		<p>Bengal Gazette collects information on a user upon the user’s access to the Bengal Gazette 
		website – (i) by registering to the site or application, (ii) subscribing to the newsletter, 
		(iii) responding to a survey or participating in a competition, (iv) logging in to a site or 
		page, etc.</p>
		
		<h4>Disclosure of Information Collected</h4>
		<p>Bengal Gazette does not sell, trade or otherwise provide personally identifiable
		information to any other parties except for those that assist Bengal Gazette in operating its
		website, conducting the business and serving the users. It may share visitor's/reader's 
		personal information internally to understand user base, promote the number of users and 
		increase user engagement.<br>
		In the event that Bengal Gazette desires to use personal information in a different way than 
		that described above it shall seek consent of the individual. Bengal Gazette may release 
		personally identifiable information if it is required to comply with the laws of Bangladesh.
		</p>

		<p>Notwithstanding anything contained in this privacy policy, Bengal Gazette may disclose or 
		share information collected including personal information to service providers, affiliate 
		companies, consultants or advisors or Partners that it has engaged to perform 
		business-related functions on its behalf. Bengal Gazette may also share the information in 
		response to legal process, or protect its interest in any forum. The information may be used 
		for investigating or preventing potentially illegal activities, or situations involving 
		potential threats to any person, us, or the services, or violations of our policies, the law 
		or our Terms of Use as well as to verify or enforce compliance with the policies governing 
		our Services. The information may as well be shared to offer market products or services to 
		the visitors/readers. However, in all these events or any other event when a personal 
		information is shared or disclosed, Bengal Gazette shall use its best endeavors to control 
		the share or disclosure and shall only share to such extent as it is required to meet the 
		purpose.</p>

		<h4>Data Retention</h4>
		<p>We shall hold visitors/readers personal information if your account exists with Bengal 
		Gazette. Notwithstanding, Bengal Gazette may retain data for a further period as per its own 
		internal data retention policy. Visitor's/reader's personal information shall be deleted upon 
		expiry of your Bengal Gazette account. Please note that there may be events when the erasing/
		deleting of information may take more time than usual, and Bengal Gazette shall not hold any 
		responsibility in such events.</p>

		<h4>Advertisement</h4>
		<p>The advertisements included in the Bengal Gazette website and mobile apps, are by 
		third-party companies & ad networks through independent ad tags, which may collect 
		information about users for which Bengal Gazette shall bear no responsibility that may arise 
		as a result of collecting and/or sharing the information’s with any other party.<br>
		Bengal Gazette shall not accept any liability that may arise as a result of any content of
		any advertisement that may appear on the Bengal Gazette website.</p>

		<h4>Third Party Advertisements and links</h4>
		<p>At the discretion of Bengal Gazette, the website or application may display or allow
		advertisements of third party services or products. These third-party sites may have separate 
		and independent privacy policies. Bengal Gazette accepts no responsibility or liability for 
		the content of advertising material, including, without limitation, any error, omission or 
		inaccuracy therein.<br>
		Bengal Gazette does not hold any responsibility for information leakage due to the visitor/
		reader accessing to a separate link, application or website, whether through a link in the 
		website or contents of Bengal Gazette.</p>

		<h4>Use of Cookies</h4>
		<p>Bengal Gazette does not collect any user data based on cookies, neither does it store any
		sort of user information that may be personal to the user.</p>

		<p>If a third party associated with the Bengal Gazette website collects user cookies upon 
		your visit to the Bengal Gazette website, Bengal Gazette does not control the use of these 
		cookies therefore you should check the relevant third-party website.</p>

		<h4>Demographic and purchase information:</h4>
		<p>We may reference other sources of demographic and other information to provide you with
		more targeted communications and promotions. We use Google Analytics, among others, to track 
		the user behavior on our website. You can opt-out of Google Analytics for Display Advertising 
		and customize Google Display Network ads using the Ads Settings options provided by Google.
		</p>

		<h4>Communication by <i>Bengal Gazette</i></h4>
		<p>From time to time, Bengal Gazette may contact its users via e-mail, phone or SMS for 
		invitation for participation in campaigns/competitions organized by Bengal Gazette, feedback, 
		survey etc, based on the information it had received from the users.</p>

		<h4>Accessing the website from outside Bangladesh</h4>
		<p>All personal information submitted by users outside Bangladesh will be processed in 
		accordance with these terms of use and privacy policy.</p>

		<h4>Governing Law</h4>
		<p>The laws that govern privacy policy of Bengal Gazette and its relationship with the user 
		is the laws of Bangladesh and any dispute regarding the use, retention, disclosure, leakage 
		or dissemination of the information or date can only be raised before the courts of 
		Bangladesh which shall have exclusive jurisdiction on this matter. The entire privacy policy 
		shall apply to all who enters the website, receives service or uses application from Bengal 
		Gazette regardless of their nationality, location, residence or place of business.</p>

		<h4>Modification of Privacy Policy</h4>
		<p>Bengal Gazette reserves the right to amend, modify, alter, or omit any terms in the 
		privacy policy at any time but the changed policy shall be immediately uploaded or updated in 
		the website. By continuing to use our services after any changes are made, you accept those 
		changes and will be bound by them. We encourage you to periodically check back and review 
		this policy so that visitors/readers will always know what information we collect, how we use 
		it, and with whom we share it.</p>

		<h4>Opt-out</h4>
		<p>If, at any time, the users prefer not to receive email containing marketing information 
		from us, then the user can simply follow the unsubscribe options at the bottom of each email.
		</p>

		<p>If the users no longer wish to have a registered account, the user may terminate the 
		account by sending an email to the following address: web.it@bengal-gazette.info</p> 
		</div>

		<?php FOOTER(); ?>
	</div>
</body>
</html>